### ISSUE TITLE
Idea - pregenerate packet builders/readers

### ISSUE THREAD

**Issue by Patbox** [janispritzkau/deno-minecraft#1]
This project looks great, but it would benefit from pregenerating packet builders/readers, so you don't need to deserialize it "by hand".  It could be automatically generated with a script based on data from https://github.com/PrismarineJS/minecraft-data

**Comment by janispritzkau** [comment]
Yeah, I've heard about minecraft-data. I though I wouldn't need to implement all the packets for a minimal Minecraft server.
I have also been experimenting a bit with Rust. The macros in Rust make make things really easy, since you only specify the field types, and the macros can generate the writer and reader code. I will have to look into Javascript/Typescript code generation.

**Comment by janispritzkau** [comment]
Oh, somehow I thought this was about https://github.com/janispritzkau/deno-minecraft-server from the email notification.

**Comment by janispritzkau** [comment]
Anyways, what are your thoughts on the protocol abstractions in https://github.com/janispritzkau/deno-minecraft-server? I would be interested to know.

**Comment by Patbox** [comment]
It looks nice! However I think having it as it's own library would be still beneficial (aka it would be easier to keep updated while using in multiple projects). And you can import it just fine from github by using raw file

**Comment by janispritzkau** [comment]
I think I would rather leave the protocol implementation to the user or a separate library, as implementing it would make this library very version dependent. Except for the handshake and status protocol, as these are unlikely to change.

**Comment by janispritzkau** [comment]
I have started implementing packets through code generation and a custom DSL (domain specific language) for the protocol here:

https://github.com/janispritzkau/deno-minecraft-protocol

I might move it to a different repository in the future though.
